## NumPy Array and basics

In [18]:
import numpy as np

### Creating array from list

The `np.array()` function is the most common way to **create NumPy arrays** from existing **Python lists** or **nested lists**.
##### Syntax:
```python
np.array(object, dtype=None)
 • object → A Python list, tuple, or nested sequence.
 • dtype (optional) → Data type of array elements (int, float, etc.).

In [19]:
arr_1d = np.array([1,2,3,4,5])
print("1D array : \n", arr_1d)

arr2_1d = np.array([1,2,3,4,5],float)
print("1D array(data type changed to float): \n", arr2_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array : \n", arr_2d)

1D array : 
 [1 2 3 4 5]
1D array(data type changed to float): 
 [1. 2. 3. 4. 5.]
2D array : 
 [[1 2 3]
 [4 5 6]]


### List vs Numpy array

To understand the difference, let's first learn the functions used:

- **Python List `*`** → Makes the list repeat its elements.  
- **NumPy Array `*`** → Multiplies each element by the given number(called scaler here).  
- **`time.time()`** → Tells the current time in seconds.  
- **List Comprehension** → Makes a new list by doing an operation on each item.  
- **`np.arange()`** → Makes a list of numbers in order, stored as a NumPy array.  

In [20]:
py_list = [1,2,3]
print("Python List Multiplication : ", py_list * 2)

np_array = np.array([1,2,3]) #element wise multiplication
print("Numpy Array Multiplication : ", np_array * 2)

#lets notice start time and end time of these multiplications to check the efficiency of both operations
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List(python) operation time : ", time.time()-start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Array(numpy) operation time : ", time.time()-start)

Python List Multiplication :  [1, 2, 3, 1, 2, 3]
Numpy Array Multiplication :  [2 4 6]

 List(python) operation time :  0.027761220932006836

 Array(numpy) operation time :  0.0008037090301513672


**Note:** NumPy is faster because it works on all elements at once using optimized code.

Imagine you have to give chocolates to 1 million kids.

 **Python lists way →** You go to each kid one by one, hand them a chocolate, then go to the next. It takes a long time because you repeat the process for each child.

 **NumPy way →** You call all the kids together, and a super-fast machine hands chocolates to everyone at the same time. The machine is built in C language, which works much faster than you can by hand.
 
That’s why NumPy finishes the job way quicker — it works on the whole group at once instead of one at a time.



### Creating Array from scratch

In this section, we explore some **array creation functions** provided by **NumPy**.

1. `np.zeros(shape)`
    - **Purpose:** Creates a new array filled entirely with **zeros**.
    - **Parameters:** 
      - `shape` *(tuple)* → Dimensions of the array (rows, columns).
    - **Example:** `np.zeros((3,4))` → Creates a **3×4 array** with all elements = `0.0`. <br> <br>

2. `np.ones(shape)`
    - **Purpose:** Creates a new array filled entirely with **ones**.
    - **Parameters:**
      - `shape` *(tuple)* → Dimensions of the array.
    - **Example:** `np.ones((2,3))` → Creates a **2×3 array** with all elements = `1.0`. <br> <br>

3. `np.full(shape, fill_value)`
    - **Purpose:** Creates a new array where **all elements have the same specified value**.
    - **Parameters:** 
      - `shape` *(tuple)* → Dimensions of the array.
      - `fill_value` *(number)* → The value to fill.
    - **Example:** `np.full((2,4), 7)` → Creates a **2×4 array** with all elements = `7`. <br> <br>

4. `np.random.random(shape)`
    - **Purpose:** Creates a new array filled with **random floating-point numbers** in the range `[0.0, 1.0)`.
    - **Parameters:**
      - `shape` *(tuple)* → Dimensions of the array.
    - **Example:** `np.random.random((2,3))` → Creates a **2×3 array** with random values. <br> <br>

5. `np.arange(start, stop, step)`
    - **Purpose:** Creates a **1D array with evenly spaced values** within a given range.
    - **Parameters:**
      - `start` *(number)* → Starting value (inclusive).
      - `stop` *(number)* → Ending value (exclusive).
      - `step` *(number)* → Difference between consecutive values.
    - **Example:** `np.arange(0, 11, 2)` → Creates `[0, 2, 4, 6, 8, 10]`.

 **Tip:** These functions are much faster and more convenient than creating lists manually, especially for large arrays.

In [21]:
zeros = np.zeros((3,4)) 
print("\nZeros Array : \n", zeros)

ones = np.ones((2,3))
print("\nOnes Array : \n", ones)

full = np.full((2,4),7)
print("\nFull Array : \n", full)

random = np.random.random((2,3))
print("\nRandom Array : \n", random)

sequnce = np.arange(0,11,2)
print("\nSequnce Array : \n", sequnce)


Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array : 
 [[1. 1. 1.]
 [1. 1. 1.]]

Full Array : 
 [[7 7 7 7]
 [7 7 7 7]]

Random Array : 
 [[0.90126779 0.21027683 0.82841696]
 [0.24560778 0.0315961  0.73137546]]

Sequnce Array : 
 [ 0  2  4  6  8 10]


### Understanding Vector, Matrix, and Tensor in NumPy

  **Vector** → A 1D array representing a list of numbers in one direction. <br>
  **1D (Vector)** → Shape like `(n,)`  

  **Matrix** → A 2D array of numbers arranged in rows and columns. <br>
  **2D (Matrix)** → Shape like `(rows, columns)` 

  **Tensor** → A multi-dimensional array (3D or higher) of numbers. <br>
  **3D+ (Tensor)** → Shape like `(depth, rows, columns)`

In [22]:
vector = np.array([1,2,3])
print("\nVector : \n", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("\nMatrix : \n", matrix)

tensor = np.array([[[1,2],[3,4],[5,6]],
                   [[7,8],[9,0],[1,2]],
                   [[3,4],[5,6],[7,8]]])
print("\nTensor : \n",tensor)


Vector : 
 [1 2 3]

Matrix : 
 [[1 2 3]
 [4 5 6]]

Tensor : 
 [[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 0]
  [1 2]]

 [[3 4]
  [5 6]
  [7 8]]]


```
Vector (1D)           Matrix (2D)              Tensor (3D)
[1, 2, 3]             [[1, 2, 3],             [[[1, 2], [3, 4], [5, 6]],
                       [4, 5, 6]]              [[7, 8], [9, 0], [1, 2]],
                                               [[3, 4], [5, 6], [7, 8]]]
```
This way: <br>
- Left → Simple row of numbers (vector). <br>
- Middle → Numbers in rows and columns (matrix). <br>
- Right → Stacked(one behind the other) matrices (tensor). <br>

### Array Attributes in NumPy

1.	**shape** – Returns a tuple showing the number of rows and columns in the array. <br>
    Example: (2, 3) → 2 rows, 3 columns. <br> <br>
2.	**ndim** – Returns the number of dimensions of the array. <br>
    Example: 2 → It’s a 2D array. <br> <br>
3.	**size** – Returns the total number of elements in the array. <br>
    Example: 6 → 2 × 3 elements. <br> <br>
4.	**dtype** – Shows the data type of elements stored in the array. <br>
    Example: int64, float32.

**Note :** These attributes do not require parentheses because they are properties, not functions.


In [23]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size : ", arr.size)
print("Data Type : ", arr.dtype)

Shape :  (2, 3)
Dimension :  2
Size :  6
Data Type :  int64


**Why similar data types?** <br>
NumPy arrays are designed for speed and efficiency. Storing all elements in the same data type allows them to be placed in contiguous memory blocks, making mathematical operations faster and reducing memory usage compared to Python lists with mixed data types. <br>
Although NumPy can store elements of different types (using dtype=object), this removes the performance benefits because data is no longer stored contiguously. We prefer similar types to take full advantage of vectorization and C-level optimizations.

### Array Reshaping

- **`reshape(new_shape)`** → Changes the shape of the array without changing its data.  
  *Example:* Turn a 1D array into 2D. Often returns a **view** (no data copied).

- **`flatten()`** → Converts any array into a 1D array **copy**.  
  Changes made to the new array **won’t affect** the original.

- **`ravel()`** → Converts any array into a 1D array **view** when possible.  
  Changes to this view **will affect** the original array.  
  Only makes a copy when a view isn’t possible (non-contiguous data).

In [24]:
arr = np.arange(12)
print("\nOriginal array : \n", arr)

reshaped = arr.reshape([3,4])
print("\nReshaped array : \n", reshaped)

flattened = reshaped.flatten()
print("\nFlattened array : \n",flattened)

raveled = reshaped.ravel()
print("\nRaveled array : \n", raveled)


Original array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


#### Difference between ravel and flatten

**Imagine :** You have a math notebook with problems arranged in 2 rows and 3 columns: <br>
Page 1 : 1   2   3 <br>
Page 2 : 4   5   6 <br> <br>
**flatten() → photocopy** <br>
	•	You make a photocopy of the notebook. <br>
	•	Now you can rip pages, scribble, or erase in the copy — your original stays safe. <br>
	•	Always makes a brand-new notebook. <br> <br>
**ravel() → rearranging your real notebook** <br>
	•	You tear out the original pages and lay them all in a single straight line. <br>
	•	If you write something on this line, the same thing shows up in the original notebook because it’s literally the same pages, just laid out differently. <br>
	•	No copy made — unless your pages were cut up weirdly before, in which case NumPy secretly makes a new notebook so it can put them in order (Like if your notebook pages were cut into little pieces and scattered, you’d have to rewrite them neatly before laying them in a line).


##### **Key differences (short)**
  **reshape() →** change shape; usually a view (no copy). <br>
  **flatten() →** always returns a copy (safe, independent). <br>
  **ravel() →** returns a view if possible, otherwise a copy (fast when view). <br> 

##### **When to use which**
  **Use ravel()** for speed when you don’t need an independent array. <br>
  **Use flatten()** when you must keep the original unchanged. <br>
  **Use reshape()** to change dimensions without copying (most efficient). <br> 

### Transpose

- **`arr.T`** → Returns the **transpose** of the array.  
- Transpose means **flipping rows into columns** and **columns into rows**.  
- Works for both 2D and higher-dimensional arrays.  

In [25]:
arr = np.array([[1,2,3],
                [4,5,6]])
transpose = arr.T
print("\nTransposed array : \n", transpose)


Transposed array : 
 [[1 4]
 [2 5]
 [3 6]]


- Does not copy data — usually returns a **view**. <br> 
when you do arr.T, NumPy doesn’t actually move the numbers around in memory.
It just changes the way it looks at them — like turning your notebook sideways instead of rewriting it.